"""File date

Revision ID: 8f7198d9411e
Revises: a11e7f255b4a
Create Date: 2019-02-01 11:49:57.612522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f7198d9411e'
down_revision = 'a11e7f255b4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('date', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file', 'date')
    # ### end Alembic commands ###
